[package]
name = "gprofile"
version = "0.1.0"
edition = "2021"
description = """
Quickly switch git user, email with ease.
"""

[[bin]]
name = "git-profile"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
